type OperatorSkillDefinition = {
  id: string;
  label: string;
  mode: "read" | "write";
  entity: string;
  summary: string;
  requiredInputs: string[];
  optionalInputs: string[];
  guardrails: string[];
  bulkSupport: "none" | "same-change-multi-row" | "per-row-multi-row";
  examples: string[];
};

const SKILLS: OperatorSkillDefinition[] = [
  {
    id: "help",
    label: "Ayuda operatoria",
    mode: "read",
    entity: "system",
    summary: "Resume lo que el bot puede hacer y como se aprueban cambios con bajo o alto riesgo.",
    requiredInputs: [],
    optionalInputs: [],
    guardrails: ["No muta datos."],
    bulkSupport: "none",
    examples: ["ayuda", "que sabes hacer"],
  },
  {
    id: "list_operator_skills",
    label: "Listar skills",
    mode: "read",
    entity: "system",
    summary: "Expone las capacidades operativas y sus reglas de uso.",
    requiredInputs: [],
    optionalInputs: [],
    guardrails: ["No muta datos."],
    bulkSupport: "none",
    examples: ["skills", "capacidades del bot"],
  },
  {
    id: "health_check",
    label: "Estado del sistema",
    mode: "read",
    entity: "system",
    summary: "Muestra volumen operativo basico: productos, stock, clientes, ordenes y conversaciones.",
    requiredInputs: [],
    optionalInputs: [],
    guardrails: ["No muta datos."],
    bulkSupport: "none",
    examples: ["estado", "health"],
  },
  {
    id: "list_products",
    label: "Listar productos",
    mode: "read",
    entity: "products",
    summary:
      "Busca productos por query (titulo/sku/marca/modelo), marca real (ej. Apple o Samsung), modelo, precio, RAM, storage, stock o imagen (has_image false = sin foto). En Telegram, si hay hasta ~20 filas, el bot manda botones por SKU para abrir la ficha. iPhone: usar query=iPhone 13, no marca=iPhone 13.",
    requiredInputs: [],
    optionalInputs: [
      "query",
      "brand",
      "model",
      "active",
      "in_stock",
      "category",
      "min_price_ars",
      "max_price_ars",
      "min_ram_gb",
      "max_ram_gb",
      "min_storage_gb",
      "max_storage_gb",
      "has_image",
      "sort_by",
      "sort_dir",
    ],
    guardrails: ["Solo lectura."],
    bulkSupport: "none",
    examples: ["productos samsung", "buscar s25 ultra"],
  },
  {
    id: "get_product_details",
    label: "Detalle completo de producto",
    mode: "read",
    entity: "products",
    summary: "Devuelve la fila completa de un producto por id, sku o slug, incluyendo todos los campos y los contadores de stock.",
    requiredInputs: ["product_ref"],
    optionalInputs: [],
    guardrails: ["Si la referencia es ambigua, detener y pedir el sku o id exacto."],
    bulkSupport: "none",
    examples: ["dame toda la fila del iphone-16-pro-max-test", "all columns for sku samsung-s25-ultra-12-512"],
  },
  {
    id: "create_product",
    label: "Crear producto",
    mode: "write",
    entity: "products",
    summary: "Crea una fila de catalogo. Idealmente con sku, title, brand, model, precio y image_url.",
    requiredInputs: ["sku", "title"],
    optionalInputs: [
      "brand",
      "model",
      "description",
      "price_amount",
      "promo_price_ars",
      "currency_code",
      "category",
      "image_url",
      "ram_gb",
      "storage_gb",
      "network",
      "color",
      "delivery_type",
      "delivery_days",
      "in_stock",
      "active",
    ],
    guardrails: [
      "Si falta sku o title, pedir aclaracion.",
      "No inventar precio ni imagen.",
      "Si viene una imagen adjunta, puede usarse como image_url.",
    ],
    bulkSupport: "none",
    examples: [
      "crear producto sku xiaomi-15t-pro-12-512 titulo Xiaomi 15T Pro 12/512 precio 1159000",
      "crear producto sku iphone-16-128 titulo iPhone 16 128 image_url https://...",
    ],
  },
  {
    id: "update_product",
    label: "Editar producto",
    mode: "write",
    entity: "products",
    summary: "Actualiza un producto existente usando product_ref por id, sku o slug. Tambien sirve para archivar con active=false.",
    requiredInputs: ["product_ref", "changes"],
    optionalInputs: [
      "title",
      "brand",
      "model",
      "description",
      "price_amount",
      "promo_price_ars",
      "image_url",
      "ram_gb",
      "storage_gb",
      "network",
      "color",
      "delivery_days",
      "in_stock",
      "active",
    ],
    guardrails: [
      "Nunca inventar product_ref.",
      "Si hay multiples coincidencias, detener y pedir referencia exacta.",
      "Solo tocar campos mencionados por el operador.",
      "Si cambia cost_usd, logistics_usd, usd_rate o cuotas_qty, recalcular pricing derivado desde settings.",
    ],
    bulkSupport: "none",
    examples: [
      "cambia el precio del samsung-s25-ultra-12-512 a 1799000",
      "actualiza la imagen del iphone-16-128 con esta foto",
    ],
  },
  {
    id: "bulk_update_products",
    label: "Edicion masiva de productos",
    mode: "write",
    entity: "products",
    summary: "Aplica el mismo cambio a varios productos en una sola operacion.",
    requiredInputs: ["product_refs[]", "changes"],
    optionalInputs: ["promo_price_ars", "active", "delivery_days", "image_url", "category", "network"],
    guardrails: [
      "Todos los productos deben resolverse sin ambiguedad.",
      "Un solo bloque de cambios compartido para todas las filas.",
      "Toda la mutacion va con confirmacion previa.",
    ],
    bulkSupport: "same-change-multi-row",
    examples: [
      "subi 3 dias de entrega a iphone-16-128, iphone-16-256 y iphone-16-plus-128",
      "desactiva samsung-a36-5g-8-256 y samsung-a07-4-128",
    ],
  },
  {
    id: "bulk_reprice_products",
    label: "Repricing masivo por lista",
    mode: "write",
    entity: "products",
    summary: "Actualiza cost_usd por producto desde una lista y recalcula pricing derivado desde settings para cada fila.",
    requiredInputs: ["items[{product_ref,cost_usd}]"],
    optionalInputs: [],
    guardrails: [
      "Cada línea debe resolver un solo producto.",
      "Si una referencia es ambigua, mostrar opciones y pedir elección.",
      "Siempre mostrar preview antes de ejecutar.",
    ],
    bulkSupport: "per-row-multi-row",
    examples: [
      "actualizá estos costos: Samsung A17 6/128 = 155, Samsung A56 8/256 = 282",
      "te paso una lista de productos con costo USD nuevo y recalculalos",
    ],
  },
  {
    id: "bulk_sync_products",
    label: "Sync masivo desde lista de proveedor",
    mode: "write",
    entity: "products",
    summary:
      "Recibe una lista pegada por el operador con secciones y líneas tipo “Producto - 123 USD”, actualiza cost_usd de los productos existentes, recalcula pricing derivado y crea automáticamente los faltantes.",
    requiredInputs: ["raw_list"],
    optionalInputs: ["create_missing", "active", "in_stock", "condition"],
    guardrails: [
      "Las líneas deben venir con precio USD explícito.",
      "Si una línea matchea varios productos distintos de forma ambigua, detener y pedir aclaración.",
      "Si una línea genérica matchea varias variantes de color del mismo modelo, actualizar todas esas variantes.",
      "Siempre mostrar preview antes de ejecutar.",
    ],
    bulkSupport: "per-row-multi-row",
    examples: [
      "te paso lista de proveedor, actualizá costos y creá los faltantes",
      "sincronizá esta lista completa de productos con USD nuevo",
    ],
  },
  {
    id: "delete_product",
    label: "Borrar producto",
    mode: "write",
    entity: "products",
    summary: "Elimina un producto de forma permanente si no tiene stock asociado. Si existen checkout intents del storefront, también los limpia automáticamente.",
    requiredInputs: ["product_ref"],
    optionalInputs: [],
    guardrails: [
      "Bloquear si el producto tiene stock.",
      "Pedir confirmacion siempre.",
    ],
    bulkSupport: "none",
    examples: ["borra el producto sku redmi-a5-4-128"],
  },
  {
    id: "bulk_delete_products",
    label: "Borrar varios productos (un OK)",
    mode: "write",
    entity: "products",
    summary:
      "Borra hasta 200 productos en una sola confirmación de Telegram: por filtro (query/marca/modelo como list_products) o por lista explícita de SKU en product_refs. Misma regla que delete_product: sin filas de stock.",
    requiredInputs: [],
    optionalInputs: ["query", "brand", "model", "active", "product_refs"],
    guardrails: [
      "Bloquear el lote si algún producto matcheado tiene stock.",
      "Siempre confirmación inline con lista preview.",
      "No ejecutar sin intención explícita de borrar muchos ítems.",
    ],
    bulkSupport: "same-change-multi-row",
    examples: [
      "borrá todos los iPhone 13 que encuentres",
      "eliminá estos sku: iphone-a, iphone-b",
    ],
  },
  {
    id: "list_stock",
    label: "Listar stock",
    mode: "read",
    entity: "stock_units",
    summary: "Busca unidades por serial, imei, sku o titulo de producto, con filtros por marca, estado, ubicacion y fechas.",
    requiredInputs: [],
    optionalInputs: ["query", "product_ref", "brand", "status", "location_code", "sold_from", "sold_to", "acquired_from", "acquired_to", "has_imei"],
    guardrails: ["Solo lectura."],
    bulkSupport: "none",
    examples: ["stock del s25 ultra", "buscar imei 356..."],
  },
  {
    id: "list_inventory_purchases",
    label: "Listar compras",
    mode: "read",
    entity: "inventory_purchases",
    summary: "Lista compras de inventario por número, proveedor o estado.",
    requiredInputs: [],
    optionalInputs: ["query", "status"],
    guardrails: ["Solo lectura."],
    bulkSupport: "none",
    examples: ["listá compras de inventario", "mostrá compras received de Juan"],
  },
  {
    id: "get_inventory_purchase_details",
    label: "Detalle de compra",
    mode: "read",
    entity: "inventory_purchases",
    summary: "Devuelve la fila completa de una compra por id o purchase_number, incluyendo funders y stock vinculado.",
    requiredInputs: ["purchase_ref"],
    optionalInputs: [],
    guardrails: ["Si la referencia es ambigua, pedir elegir la compra correcta."],
    bulkSupport: "none",
    examples: ["dame la compra PUR-AB12CD34", "detalle completo de la compra 15"],
  },
  {
    id: "list_meta_campaigns",
    label: "Listar campañas Meta",
    mode: "read",
    entity: "meta_campaigns",
    summary: "Lista campañas del ad account por nombre o estado, por ejemplo activas o pausadas.",
    requiredInputs: [],
    optionalInputs: ["query", "status", "limit"],
    guardrails: ["Solo lectura contra Meta Ads."],
    bulkSupport: "none",
    examples: ["mostrame campañas activas", "campañas pausadas de remarketing"],
  },
  {
    id: "list_meta_ad_sets",
    label: "Listar conjuntos Meta",
    mode: "read",
    entity: "meta_ad_sets",
    summary: "Lista ad sets del ad account por nombre o estado.",
    requiredInputs: [],
    optionalInputs: ["query", "status", "limit"],
    guardrails: ["Solo lectura contra Meta Ads."],
    bulkSupport: "none",
    examples: ["mostrame ad sets activos", "conjuntos pausados"],
  },
  {
    id: "list_meta_ads",
    label: "Listar anuncios Meta",
    mode: "read",
    entity: "meta_ads",
    summary: "Lista anuncios del ad account por nombre o estado.",
    requiredInputs: [],
    optionalInputs: ["query", "status", "limit"],
    guardrails: ["Solo lectura contra Meta Ads."],
    bulkSupport: "none",
    examples: ["mostrame ads activos", "anuncios pausados"],
  },
  {
    id: "update_meta_campaign",
    label: "Editar campaña Meta",
    mode: "write",
    entity: "meta_campaigns",
    summary: "Permite activar, pausar o cambiar presupuesto diario/vitalicio de una campaña.",
    requiredInputs: ["campaign_ref", "changes"],
    optionalInputs: ["status", "daily_budget", "lifetime_budget"],
    guardrails: [
      "Si la referencia es ambigua, mostrar opciones y pedir elección.",
      "Si cambia presupuesto, mandar solo daily_budget o lifetime_budget según corresponda.",
      "Siempre pasa por aprobar / editar / cancelar.",
    ],
    bulkSupport: "none",
    examples: ["pausá la campaña remarketing marzo", "subí el presupuesto de la campaña test a 15000"],
  },
  {
    id: "update_meta_ad_set",
    label: "Editar ad set Meta",
    mode: "write",
    entity: "meta_ad_sets",
    summary: "Permite activar, pausar o cambiar presupuesto diario/vitalicio de un ad set.",
    requiredInputs: ["ad_set_ref", "changes"],
    optionalInputs: ["status", "daily_budget", "lifetime_budget"],
    guardrails: [
      "Si la referencia es ambigua, mostrar opciones y pedir elección.",
      "Siempre pasa por aprobar / editar / cancelar.",
    ],
    bulkSupport: "none",
    examples: ["activá el ad set ventas frías", "pausá el conjunto broad 18-45"],
  },
  {
    id: "update_meta_ad",
    label: "Editar anuncio Meta",
    mode: "write",
    entity: "meta_ads",
    summary: "Permite activar o pausar un anuncio puntual.",
    requiredInputs: ["ad_ref", "changes"],
    optionalInputs: ["status"],
    guardrails: [
      "Si la referencia es ambigua, mostrar opciones y pedir elección.",
      "Siempre pasa por aprobar / editar / cancelar.",
    ],
    bulkSupport: "none",
    examples: ["pausá el anuncio video hook 3", "activá el ad del iphone 16"],
  },
  {
    id: "get_stock_details",
    label: "Detalle completo de stock",
    mode: "read",
    entity: "stock_units",
    summary: "Devuelve la fila completa de una unidad de stock por id, serial, imei o sku.",
    requiredInputs: ["stock_ref"],
    optionalInputs: [],
    guardrails: ["Si la referencia es ambigua, detener y pedir id, serial o imei exacto."],
    bulkSupport: "none",
    examples: ["dame toda la fila del imei 356...", "full row stock 44"],
  },
  {
    id: "create_inventory_purchase",
    label: "Crear compra",
    mode: "write",
    entity: "inventory_purchases",
    summary: "Crea una compra de inventario con total, proveedor y funders.",
    requiredInputs: [],
    optionalInputs: ["supplier_name", "currency_code", "total_amount", "status", "acquired_at", "notes", "funders[]", "metadata"],
    guardrails: [
      "No inventar funders ni montos.",
      "Si el total no está claro, dejarlo en null o pedirlo.",
    ],
    bulkSupport: "none",
    examples: [
      "creá una compra de 5000 USD financiada 50/50 por Fran y Agus",
      "registrá compra draft proveedor Juan con total 1200 usd",
    ],
  },
  {
    id: "update_inventory_purchase",
    label: "Editar compra",
    mode: "write",
    entity: "inventory_purchases",
    summary: "Actualiza proveedor, total, estado, notas o funders de una compra existente.",
    requiredInputs: ["purchase_ref", "changes"],
    optionalInputs: ["supplier_name", "total_amount", "status", "acquired_at", "notes", "funders[]"],
    guardrails: [
      "Resolver la compra exacta antes de editar.",
      "Si cambia el reparto de funders, mostrar el lote completo antes de aprobar.",
    ],
    bulkSupport: "none",
    examples: [
      "cambiá la compra PUR-AB12CD34 a received",
      "actualizá funders de la compra 18 a 60/40",
    ],
  },
  {
    id: "create_stock_unit",
    label: "Crear unidad de stock",
    mode: "write",
    entity: "stock_units",
    summary: "Registra una unidad fisica vinculada a un producto y obligatoriamente a una compra.",
    requiredInputs: ["product_ref", "inventory_purchase_ref"],
    optionalInputs: [
      "serial_number",
      "imei_1",
      "imei_2",
      "status",
      "location_code",
      "cost_amount",
      "currency_code",
      "color",
      "battery_health",
      "metadata",
    ],
    guardrails: [
      "Resolver producto exacto antes de crear.",
      "Toda unidad nueva debe quedar asociada a una compra existente o a una compra nueva creada en la misma operacion.",
      "Usar IMEI 1 e IMEI 2 para telefonos dual-SIM.",
    ],
    bulkSupport: "none",
    examples: [
      "crear stock para samsung-s25-ultra-12-512 imei1 123 imei2 456",
      "crear unidad para iphone-16-128 serial SN001 location_code SALTA",
    ],
  },
  {
    id: "create_stock_from_images",
    label: "Crear stock desde fotos",
    mode: "write",
    entity: "stock_units",
    summary: "Toma las imágenes recientes del chat, extrae IMEIs/seriales, muestra preview y crea las unidades de stock vinculadas a una compra.",
    requiredInputs: ["product_ref"],
    optionalInputs: ["inventory_purchase_ref", "cost_amount", "currency_code", "status", "location_code", "acquired_at", "metadata"],
    guardrails: [
      "Usar solo el lote reciente de imágenes del chat.",
      "Nunca crear stock sin compra asociada; si falta, pedir elegir una compra o crearla.",
      "Si un IMEI ya existe, bloquear el lote.",
      "Siempre mostrar preview antes de ejecutar.",
    ],
    bulkSupport: "per-row-multi-row",
    examples: [
      "creá stock del iPhone 17 Pro Max con estas fotos",
      "tomá estas imágenes y cargá stock del A17 en SALTA",
    ],
  },
  {
    id: "create_inventory_purchase_from_images",
    label: "Compra + stock desde fotos",
    mode: "write",
    entity: "inventory_purchases",
    summary: "Con las imágenes recientes crea una compra de inventario y las unidades de stock vinculadas.",
    requiredInputs: ["product_ref"],
    optionalInputs: ["supplier_name", "currency_code", "total_amount", "funders[]", "cost_amount", "location_code", "acquired_at", "notes", "metadata"],
    guardrails: [
      "Extraer y validar IMEIs antes de crear.",
      "Si hay duplicados o faltan coincidencias confiables, detener.",
      "Siempre pedir aprobación con preview.",
    ],
    bulkSupport: "per-row-multi-row",
    examples: [
      "con estas fotos cargá una compra de 10 iPhone 17 Pro Max financiada 50/50",
      "registrá compra desde estas imágenes proveedor Juan 3200 usd",
    ],
  },
  {
    id: "update_stock_unit",
    label: "Editar unidad de stock",
    mode: "write",
    entity: "stock_units",
    summary: "Actualiza una unidad por id, serial, imei o sku.",
    requiredInputs: ["stock_ref", "changes"],
    optionalInputs: ["status", "location_code", "imei_1", "imei_2", "serial_number", "cost_amount", "sold_at"],
    guardrails: [
      "Si el stock_ref es ambiguo, detener.",
      "Solo editar campos pedidos por el operador.",
    ],
    bulkSupport: "none",
    examples: ["marca como vendido el imei 356...", "mueve el stock 44 a local SALTA"],
  },
  {
    id: "update_stock_status_from_images",
    label: "Actualizar stock desde fotos",
    mode: "write",
    entity: "stock_units",
    summary: "Extrae IMEIs/seriales de las imágenes recientes, los cruza contra stock existente y cambia el estado.",
    requiredInputs: ["status"],
    optionalInputs: ["sold_at", "location_code"],
    guardrails: [
      "Si una imagen no matchea stock existente, detener.",
      "Para ventas, si no llega sold_at usar ahora.",
      "Siempre mostrar preview antes de ejecutar.",
    ],
    bulkSupport: "per-row-multi-row",
    examples: [
      "con estas fotos marcá como vendido el stock",
      "tomá estas imágenes y pasá esas unidades a reserved",
    ],
  },
  {
    id: "delete_stock_unit",
    label: "Borrar unidad de stock",
    mode: "write",
    entity: "stock_units",
    summary: "Elimina una unidad fisica puntual por id, serial o IMEI.",
    requiredInputs: ["stock_ref"],
    optionalInputs: [],
    guardrails: [
      "Si la referencia es ambigua, detener.",
      "No borrar stock vendido.",
      "Pedir aprobacion previa.",
    ],
    bulkSupport: "none",
    examples: ["borra el stock 44", "elimina la unidad con imei 356..."],
  },
  {
    id: "bulk_update_stock_units",
    label: "Edicion masiva de stock",
    mode: "write",
    entity: "stock_units",
    summary: "Aplica el mismo cambio a varias unidades de stock.",
    requiredInputs: ["stock_refs[]", "changes"],
    optionalInputs: ["status", "location_code", "sold_at", "cost_amount"],
    guardrails: [
      "Todas las unidades deben resolverse de forma exacta.",
      "Un unico set de cambios por lote.",
    ],
    bulkSupport: "same-change-multi-row",
    examples: [
      "mueve a SALTA los stock 41, 42 y 43",
      "marca como reserved los imei 123 y 456",
    ],
  },
  {
    id: "list_settings",
    label: "Listar settings",
    mode: "read",
    entity: "settings",
    summary: "Busca claves de configuracion por key.",
    requiredInputs: [],
    optionalInputs: ["query"],
    guardrails: ["Solo lectura."],
    bulkSupport: "none",
    examples: ["settings store", "buscar whatsapp"],
  },
  {
    id: "get_setting_details",
    label: "Detalle de setting",
    mode: "read",
    entity: "settings",
    summary: "Devuelve la fila completa de un setting por key, incluyendo value y description.",
    requiredInputs: ["key"],
    optionalInputs: [],
    guardrails: ["Si la key es ambigua, detener y pedir la key exacta."],
    bulkSupport: "none",
    examples: ["dame el setting store completo", "full row pricing_default_usd_rate"],
  },
  {
    id: "update_setting",
    label: "Guardar setting",
    mode: "write",
    entity: "settings",
    summary: "Crea o actualiza una key/value en settings.",
    requiredInputs: ["key", "value"],
    optionalInputs: ["description"],
    guardrails: [
      "No borrar ni sobreescribir store sin confirmacion consciente.",
      "El value debe ser JSON valido.",
    ],
    bulkSupport: "none",
    examples: ["setea store_whatsapp a 543875319940", "actualiza pricing_default_usd_rate a 1460"],
  },
  {
    id: "delete_setting",
    label: "Borrar setting",
    mode: "write",
    entity: "settings",
    summary: "Elimina una key especifica de settings.",
    requiredInputs: ["key"],
    optionalInputs: [],
    guardrails: [
      "No borrar la key store.",
      "Confirmacion obligatoria.",
    ],
    bulkSupport: "none",
    examples: ["borra el setting customer_cards_blocked"],
  },
  {
    id: "create_customer",
    label: "Crear cliente",
    mode: "write",
    entity: "customers",
    summary: "Crea un cliente con external_ref, telefono o email.",
    requiredInputs: ["external_ref | phone | email"],
    optionalInputs: ["first_name", "last_name", "notes"],
    guardrails: ["Debe existir al menos un identificador externo."],
    bulkSupport: "none",
    examples: ["crear cliente Francisco Alderete telefono 387..."],
  },
  {
    id: "update_customer",
    label: "Editar cliente",
    mode: "write",
    entity: "customers",
    summary: "Actualiza un cliente por id, telefono, email o external_ref.",
    requiredInputs: ["customer_ref", "changes"],
    optionalInputs: ["first_name", "last_name", "phone", "email", "notes"],
    guardrails: ["Si hay varias coincidencias, pedir referencia exacta."],
    bulkSupport: "none",
    examples: ["actualiza el telefono del cliente 43 a 387..."],
  },
  {
    id: "get_customer_details",
    label: "Detalle completo de cliente",
    mode: "read",
    entity: "customers",
    summary: "Devuelve la fila completa de un cliente por id, telefono, email o external_ref.",
    requiredInputs: ["customer_ref"],
    optionalInputs: [],
    guardrails: ["Si la referencia es ambigua, pedir la exacta."],
    bulkSupport: "none",
    examples: ["dame toda la fila del cliente 43", "full row customer 387..."],
  },
];

function renderSkill(skill: OperatorSkillDefinition) {
  return [
    `${skill.id} (${skill.mode}, ${skill.entity})`,
    `- ${skill.summary}`,
    skill.requiredInputs.length > 0 ? `- required: ${skill.requiredInputs.join(", ")}` : "",
    skill.optionalInputs.length > 0 ? `- optional: ${skill.optionalInputs.join(", ")}` : "",
    skill.guardrails.length > 0 ? `- guardrails: ${skill.guardrails.join(" | ")}` : "",
    skill.bulkSupport !== "none" ? `- bulk: ${skill.bulkSupport}` : "",
    `- examples: ${skill.examples.join(" || ")}`,
  ]
    .filter(Boolean)
    .join("\n");
}

export function buildOperatorSkillGuide() {
  return [
    "Operator skill registry:",
    "The model must choose only from the skills below.",
    "Every write skill is deterministic and validated before execution.",
    "Exact low-risk single-row edits can auto-execute. Higher-risk writes go through approve/edit/cancel review.",
    "If required inputs are missing, the model must ask only for the missing fields.",
    "If a reference is ambiguous, the model must stop and ask the operator to choose from concrete options.",
    ...SKILLS.map(renderSkill),
  ].join("\n");
}

export function buildOperatorSkillListText() {
  const sections = [
    "Capacidades activas del bot:",
    ...SKILLS.map((skill) => `• ${skill.id}: ${skill.summary}`),
    "",
    "Cambios puntuales de bajo riesgo pueden ejecutarse directo.",
    "El resto queda pendiente con botones de aprobar / editar / cancelar.",
  ];

  return sections.join("\n");
}

export function buildOperatorHelpText() {
  const reads = SKILLS.filter((skill) => skill.mode === "read").map((skill) => `• ${skill.id}`);
  const writes = SKILLS.filter((skill) => skill.mode === "write").map((skill) => `• ${skill.id}`);

  return [
    "TechnoStore Ops via Telegram",
    "",
    "Podés escribir en lenguaje natural o usar los botones del menú.",
    "",
    "Lectura:",
    ...reads,
    "",
    "Mutaciones seguras:",
    ...writes,
    "",
    "Reglas:",
    "• Cambios exactos de bajo riesgo pueden ejecutarse sin confirmación manual.",
    "• Cambios más sensibles quedan pendientes para aprobar, editar o cancelar.",
    "• Si cambiás cost_usd, logistics_usd, usd_rate o cuotas_qty, el pricing derivado se recalcula desde settings.",
    "• También puedo hacer repricing masivo desde una lista y trabajar con imágenes recientes para stock/compras.",
    "• Si falta un dato, el bot tiene que pedirlo.",
    "• Si una referencia es ambigua, el bot muestra opciones para elegir.",
    "• Los cambios masivos pueden aplicar el mismo cambio a varias filas o un repricing distinto por línea.",
  ].join("\n");
}
